$(function(){
	$("#search").click(function(){
		var pid=$("#pid").val();
		if(pid==""){
			alert("请输入要查询的病历号")
		}else if(isNaN(pid)){
			alert("病历号必须为数字");
		}else{
			$.ajax({
				type:"post",
				url:"getPatientByNo/"+pid,
				data:{},
				dataType:"json",
				success:function(msg){
					if(msg.patient_ID==0){
						alert("系统中不存在该患者");
					}else{
						$("#patient_ID").val(msg.patient_ID);
						$("#patient_name").val(msg.patient_name);
						if(msg.gender=="男"){
							$("#gender1")[0].checked=true;
						}else{
							$("#gender0")[0].checked=true;
						}
						$("#register_date").val(msg.register_date);
						$("#patient_identity").val(msg.patient_identity);
						$("#register_level_id").val(msg.level.register_level_name);
						if(msg.visited_type==1){
							$("#visited_type").html("未诊");
							$("#refund")[0].disabled=false;
							
						}else{
							$("#visited_type").html("已诊");
							
						}
						if(msg.visited_type==3){
							$("#status").html("退号")
						}else{
							$("#status").html("正常");
						}
						$("#department_id").val(msg.department.department_name);
						$("#doctor_id").val(msg.doctor.doctor_name);
					}
					
				}
			});
		}
	});
	//退号
	$("#refund").click(function(){
		$.ajax({
			type:"post",
			url:"refundPatient/"+$("#patient_ID").val(),
			data:{},
			dataType:"json",
			success:function(msg){
				$("#status").html("退号");
				alert("退费成功");
				$("#refund")[0].disabled=true;
			}
		});
	});
	//门诊挂号，回到挂号页面
	$("#div1_1").click(function(){
		location.href="outpatient_register.html";
	});
	//进入门诊收费页面
	$("#div1_2").click(function(){
		location.href="outpatient_pay.html";
	});
})